### ISSUE TITLE
api?

### ISSUE THREAD

**Issue by roshan110** [annotationsatharvard/catcha#56]
what is API?

**Comment by jmiranda** [comment]
Hey Roshan -- I'm not sure how much detail you're looking for, but API stands for application programming interface (http://en.wikipedia.org/wiki/Application_programming_interface). It is a way for applications to communicate with one another. Specifically, the CATCH API is an annotation repostitory (database) and REST API (web service) that allows client applications to store and retrieve annotations. 

Let me know if you have any other questions.

**Comment by roshan110** [comment]
thanks
