### ISSUE TITLE
path to submodules wrong?

### ISSUE THREAD

**Issue by nicolasfranck** [annotationsatharvard/catcha#78]
in this file

    grails-app/conf/BuildConfig.groovy

the paths to the submodules is:

    grails.plugin.location.'af-shared' = '../annotationframework/AfShared'
    grails.plugin.location.'af-security' = '../annotationframework/AfSecurity'
    grails.plugin.location.'af-persistence' = '../annotationframework/AfPersistence'

that causes the compilation to fail. Removing the "../" solves this

**Comment by jmiranda** [comment]
Thank you. I may have inadvertently changed the developer instructions to have you clone the annotationframework plugins within the catcha root directory. However, I would actually recommend moving the annotationframework directory to be at the same level as the catcha source directory. 

So for example, my development environment looks like this:

/home/jmiranda/git/catcha
/home/jmiranda/git/annotationframework/AfShared
/home/jmiranda/git/annotationframework/AfSecurity
/home/jmiranda/git/annotationframework/AfPersistence

Sorry for the confusion. I will fix the documentation accordingly.
