### ISSUE TITLE
Image server version

### ISSUE THREAD

**Issue by xcompass** [annotationsatharvard/catcha#80]
Hi @jmiranda,

we are trying to deploy this tool and using it with edX Edge. It seems the JS code on the edx side is using IIIF API 1.1. Does it support API 2.0? We are also trying to deploy Loris to server the images. The latest version is using API 2.0. If this doesn't support API 2.0, we have to deploy Loris 1.x. Is it the case for Harvard? 

Also how do you convert an image to IIIF format to be served with Loris? It seems Loris doesn't have any way to convert an image. Do I need another tool to do that? thanks.

**Comment by jmiranda** [comment]
Hey @xcompass - The CATCH API doesn't actually have anything to do with the image server. The API is just responsible for storing annotations that are created on top of the various media types (e.g. text, image, video).

**Comment by jmiranda** [comment]
@lduarte1991 Do you have any input on this?

**Comment by xcompass** [comment]
Thanks @jmiranda. I understand CATCH API has nothing to do with image server. I thought you guys developed the code in edX to communicate with CATCH API. If it is not you guys, do you know who did it? Thanks.

**Comment by jmiranda** [comment]
I'm hoping Luis can answer that for you. I'll follow up with him tomorrow.

**Comment by xcompass** [comment]
Thanks @lduarte1991 for the info. 

I finally got it working now. I have to use Loris 1.x since xmodule is using openseadragon 0.9.131, which only supports IIIF API 1.1. In case someone is on the same boat. Here is the docker image: https://hub.docker.com/r/ubcctlt/loris-docker/
